name: still_controller
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'  # Добавлено ограничение SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.2.2
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true